ALL_EMOTE_LIST: list[tuple[str, str]] = [
    ("Rest", "idle-sit-idle-cute"),
    ("Zombie", "idle_zombie"),
    ("Relaxed", "idle_layingdown2"),
    ("Attentive", "idle_layingdown"),
    ("Sleepy", "idle-sleep"),
    ("Pouty Face", "idle-sad"),
    ("Posh", "idle-posh"),
    ("Sleepy", "idle-loop-tired"),
    ("Tap Loop", "idle-loop-tapdance"),
    ("Sit", "idle-loop-sitfloor"),
    ("Shy", "idle-loop-shy"),
    ("Bummed", "idle-loop-sad"),
    ("Chillin'", "idle-loop-happy"),
    ("Annoyed", "idle-loop-annoyed"),
    ("Aerobics", "idle-loop-aerobics"),
    ("Ponder", "idle-lookup"),
    ("Hero Pose", "idle-hero"),
    ("Relaxing", "idle-floorsleeping2"),
    ("Cozy Nap", "idle-floorsleeping"),
    ("Enthused", "idle-enthusiastic"),
    ("Boogie Swing", "idle-dance-swinging"),
    ("Feel The Beat", "idle-dance-headbobbing"),
    ("Irritated", "idle-angry"),
    ("Yes", "emote-yes"),
    ("I Believe I Can Fly", "emote-wings"),
    ("The Wave", "emote-wave"),
    ("Tired", "emote-tired"),
    ("Think", "emote-think"),
    ("Theatrical", "emote-theatrical"),
    ("Tap Dance", "emote-tapdance"),
    ("Super Run", "emote-superrun"),
    ("Super Punch", "emote-superpunch"),
    ("Sumo Fight", "emote-sumo"),
    ("Thumb Suck", "emote-suckthumb"),
    ("Splits Drop", "emote-splitsdrop"),
    ("Snowball Fight!", "emote-snowball"),
    ("Snow Angel", "emote-snowangel"),
    ("Shy", "emote-shy"),
    ("Secret Handshake", "emote-secrethandshake"),
    ("Sad", "emote-sad"),
    ("Rope Pull", "emote-ropepull"),
    ("Roll", "emote-roll"),
    ("ROFL!", "emote-rofl"),
    ("Robot", "emote-robot"),
    ("Rainbow", "emote-rainbow"),
    ("Proposing", "emote-proposing"),
    ("Peekaboo!", "emote-peekaboo"),
    ("Peace", "emote-peace"),
    ("Panic", "emote-panic"),
    ("No", "emote-no"),
    ("Ninja Run", "emote-ninjarun"),
    ("Night Fever", "emote-nightfever"),
    ("Monster Fail", "emote-monster_fail"),
    ("Model", "emote-model"),
    ("Flirty Wave", "emote-lust"),
    ("Level Up!", "emote-levelup"),
    ("Amused", "emote-laughing2"),
    ("Laugh", "emote-laughing"),
    ("Kiss", "emote-kiss"),
    ("Super Kick", "emote-kicking"),
    ("Jump", "emote-jumpb"),
    ("Judo Chop", "emote-judochop"),
    ("Imaginary Jetpack", "emote-jetpack"),
    ("Hug Yourself", "emote-hugyourself"),
    ("Sweating", "emote-hot"),
    ("Hero Entrance", "emote-hero"),
    ("Hello", "emote-hello"),
    ("Headball", "emote-headball"),
    ("Harlem Shake", "emote-harlemshake"),
    ("Happy", "emote-happy"),
    ("Handstand", "emote-handstand"),
    ("Greedy Emote", "emote-greedy"),
    ("Graceful", "emote-graceful"),
    ("Moonwalk", "emote-gordonshuffle"),
    ("Ghost Float", "emote-ghost-idle"),
    ("Gangnam Style", "emote-gangnam"),
    ("Frolic ", "emote-frollicking"),
    ("Faint", "emote-fainting"),
    ("Clumsy", "emote-fail2"),
    ("Fall", "emote-fail1"),
    ("Face Palm", "emote-exasperatedb"),
    ("Exasperated", "emote-exasperated"),
    ("Elbow Bump", "emote-elbowbump"),
    ("Disco", "emote-disco"),
    ("Blast Off", "emote-disappear"),
    ("Faint Drop", "emote-deathdrop"),
    ("Collapse", "emote-death2"),
    ("Revival", "emote-death"),
    ("Dab", "emote-dab"),
    ("Curtsy", "emote-curtsy"),
    ("Confusion", "emote-confused"),
    ("Cold", "emote-cold"),
    ("Charging", "emote-charging"),
    ("Bunny Hop", "emote-bunnyhop"),
    ("Bow", "emote-bow"),
    ("Boo", "emote-boo"),
    ("Home Run!", "emote-baseball"),
    ("Falling Apart", "emote-apart"),
    ("Thumbs Up", "emoji-thumbsup"),
    ("GhostFloat", "emote-ghost-idle"),
    ("CozyNap", "idle-floorsleeping"),
    ("Point", "emoji-there"),
    ("Sneeze", "emoji-sneeze"),
    ("Smirk", "emoji-smirking"),
    ("Sick", "emoji-sick"),
    ("Gasp", "emoji-scared"),
    ("Punch", "emoji-punch"),
    ("Pray", "emoji-pray"),
    ("Stinky", "emoji-poop"),
    ("Naughty", "emoji-naughty"),
    ("Mind Blown", "emoji-mind-blown"),
    ("Lying", "emoji-lying"),
    ("Levitate", "emoji-halo"),
    ("Fireball Lunge", "emoji-hadoken"),
    ("Give Up", "emoji-give-up"),
    ("Tummy Ache", "emoji-gagging"),
    ("Flex", "emoji-flex"),
    ("Stunned", "emoji-dizzy"),
    ("Cursing Emote", "emoji-cursing"),
    ("Sob", "emoji-crying"),
    ("Clap", "emoji-clapping"),
    ("Raise The Roof", "emoji-celebrate"),
    ("Arrogance", "emoji-arrogance"),
    ("Angry", "emoji-angry"),
    ("Vogue Hands", "dance-voguehands"),
    ("Savage Dance", "dance-tiktok8"),
    ("Don't Start Now", "dance-tiktok2"),
    ("Yoga Flow", "dance-spiritual"),
    ("Smoothwalk", "dance-smoothwalk"),
    ("Ring on It", "dance-singleladies"),
    ("Let's Go Shopping", "dance-shoppingcart"),
    ("Russian Dance", "dance-russian"),
    ("Robotic", "dance-robotic"),
    ("Penny's Dance", "dance-pennywise"),
    ("Orange Juice Dance", "dance-orangejustice"),
    ("Rock Out", "dance-metal"),
    ("Karate", "dance-martial-artist"),
    ("Macarena", "dance-macarena"),
    ("Hands in the Air", "dance-handsup"),
    ("Floss", "dance-floss"),
    ("Duck Walk", "dance-duckwalk"),
    ("Breakdance", "dance-breakdance"),
    ("K-Pop Dance", "dance-blackpink"),
    ("Push Ups", "dance-aerobics"),
    ("Hyped", "emote-hyped"),
    ("Jinglebell", "dance-jinglebell"),
    ("Nervous", "idle-nervous"),
    ("Toilet", "idle-toilet"),
    ("Attention", "emote-attention"),
    ("Astronaut", "emote-astronaut"),
    ("Dance Zombie", "dance-zombie"),
    ("Ghost", "emoji-ghost"),
    ("Heart Eyes", "emote-hearteyes"),
    ("Swordfight", "emote-swordfight"),
    ("TimeJump", "emote-timejump"),
    ("Snake", "emote-snake"),
    ("Heart Fingers", "emote-heartfingers"),
    ("Heart Shape", "emote-heartshape"),
    ("Hug", "emote-hug"),
    ("laidback", "sit-open"),
    ("hipshake", "dance-hipshake"),
    ("slap", "emote-slap"),
    ("jingle", "dance-jinglebell"),
    ("dontstartnow", "dance-tiktok2"),
    ("frog", "emote-frog"),
    ("smooch", "emote-kissing"),
    ("cutesalute","emote-cutesalute"),
    ("cute","emote-cute"),
    ("snowball","emote-snowball"),
    ("bashful","emote-shy2"),
    ("fallingapart","emote-apart")
]